# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
destination: docs/
title: Combinatorial species in TTU
email: fosco.loregian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A reading seminar on Joyal's combinatorial species
baseurl: "/species" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

antex:
  url_path_prefix: /species
  aliases:
    # disable most aliases and let KaTeX render simple
    display_math: false
    inline_math: false
    inline_macro: false

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: null # lets KaTeX parse display math on client side
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - flake.nix
  - flake.lock
  - gemset.nix
  - vendor/
  - drafts

collections:
  lectures:
    output: true